services:
  db:
    image: postgres:16
    container_name: jobqueue_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    container_name: jobqueue_api
    ports:
      - "8000:8000"

    environment:
        - DB_NAME=${DB_NAME}
        - DB_HOST=db  
        - DB_PORT=5432
        - DB_USER=${DB_USER}
        - DB_PASSWORD=${DB_PASSWORD}
    depends_on:
      db:
        condition: service_healthy

  # worker:
  #   build: .
  #   container_name: jobqueue_worker
  #   command: python worker.py 
  #   environment:
  #     - DB_HOST=db
  #     - DB_PORT=5432
  #     - DB_NAME=${DB_NAME}
  #     - DB_USER=${DB_USER}
  #     - DB_PASSWORD=${DB_PASSWORD}
  #   depends_on:
  #     db:
  #       condition: service_healthy 

volumes:
  postgres_data: